2019-05-30 17:50:03,422 ERROR: Exception on /explore [GET] [in /home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/codemantra/Documents/Learning/Python/microblog/app/routes.py", line 154, in explore
    page = request.args.get(page, 1, type=int)
UnboundLocalError: local variable 'page' referenced before assignment
2019-05-30 17:50:41,910 INFO: Microblog Startup [in /home/codemantra/Documents/Learning/Python/microblog/app/__init__.py:52]
2019-05-30 17:50:46,132 ERROR: Exception on /explore [GET] [in /home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/codemantra/Documents/Learning/Python/microblog/app/routes.py", line 154, in explore
    page = request.args.get(page, 1, type=int)
UnboundLocalError: local variable 'page' referenced before assignment
2019-05-30 17:52:26,203 INFO: Microblog Startup [in /home/codemantra/Documents/Learning/Python/microblog/app/__init__.py:52]
2019-05-30 18:18:51,589 INFO: Microblog Startup [in /home/codemantra/Documents/Learning/Python/microblog/app/__init__.py:52]
2019-05-30 18:19:14,785 ERROR: Exception on /index [GET] [in /home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/codemantra/Documents/Learning/Python/microblog/app/routes.py", line 34, in index
    return render_template('index.html', title='Home', posts=posts.item, next_url=next_url, prev_url=prev_url)
AttributeError: 'Pagination' object has no attribute 'item'
2019-05-30 18:20:48,002 INFO: Microblog Startup [in /home/codemantra/Documents/Learning/Python/microblog/app/__init__.py:52]
2019-05-30 18:52:54,612 INFO: Microblog Startup [in /home/codemantra/Documents/Learning/Python/microblog/app/__init__.py:52]
2019-05-30 18:53:00,091 ERROR: Exception on /user/shahid1 [GET] [in /home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/codemantra/Documents/Learning/Python/microblog/app/routes.py", line 96, in user
    return render_template('user.html', user = user, posts = posts)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/codemantra/Documents/Learning/Python/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/codemantra/Documents/Learning/Python/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/codemantra/Documents/Learning/Python/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/codemantra/Documents/Learning/Python/microblog/app/templates/user.html", line 29, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
